spring:
  application:
    name: eureka-server
---
spring:
  profiles: node1
server:
  port: 9001

eureka:
  instance:
    hostname: node1
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka,http://localhost:9003/eureka


---
spring:
  profiles: node2
server:
  port: 9002

eureka:
  instance:
    hostname: node2
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka,http://localhost:9003/eureka


---
spring:
  profiles: node3
server:
  port: 9003

eureka:
  instance:
    hostname: node3
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka,http://localhost:9002/eureka

